FROM xosproject/xos-synchronizer-base:candidate

ADD . /opt/xos/synchronizers/onos

ENTRYPOINT []

WORKDIR "/opt/xos/synchronizers/onos"

CMD bash -c "cd /opt/xos/synchronizers/onos; ./run-from-api.sh"
